name: 'Chromatic (manual)'
on:
    issue_comment:
        types: [created]
jobs:
    check_comments:
        name: Detect comment
        if: ${{ github.event.issue.pull_request }}
        runs-on: ubuntu-latest
        steps:
            - if: contains(github.event.comment.body, '/chromatic')
              uses: actions/github-script@v7
              with:
                  script: |
                      github.rest.issues.createComment({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.issue.number,
                        body: 'MANUAL ACTION EXECUTED'
                      })
