name: 'Chromatic (manual)'
on:
    pull_request:
        types: [labeled]
jobs:
    check_comments:
        name: Run Chromatic
        if: ${{ github.event.label.name == 'chromatic' }}
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
        steps:
            - uses: actions/github-script@v7
              with:
                  script: |
                      console.log(context)
                      github.rest.issues.createComment({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.issue.number,
                        body: 'MANUAL ACTION EXECUTED'
                      })
