name: 'Chromatic'
on:
    pull_request_review:
        types: [submitted]
    pull_request:
        types: [opened, synchronize, reopened]
jobs:
    # check_approval:
    #     name: Check PR Approvals
    #     uses: ./.github/workflows/min-pr-approvals-count.yml
    #     with:
    #         pull-number: ${{ github.event.pull_request.number }}
    #         min-approval-count: 1
    #     secrets:
    #         github-token: ${{ secrets.GITHUB_TOKEN }}
    chromatic:
        name: Run Chromatic
        runs-on: ubuntu-latest
        # needs: check_approval
        # if: needs.check_approval.outputs.is_approved == 'true'
        permissions:
            pull-requests: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Setup package manager
              uses: pnpm/action-setup@v3
              with:
                  version: 10
                  run_install: false
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 22.15.0
                  cache: 'pnpm'
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Run Chromatic
              uses: chromaui/action@latest
              with:
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                  buildScriptName: 'build:storybook'
                  onlyChanged: true
                  zip: true
            - name: Add PR Comment
              if: success()
              uses: actions/github-script@v7
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      const chromaticUrl = '${{ steps.chromatic.outputs.url }}';
                      const changesCount = ${{ steps.chromatic.outputs.changeCount }};

                      const hasChanges = changesCount > 0;

                      const statusIcon = hasChanges ? '❌' : '✅';
                      const statusText = hasChanges ? 'CHANGES_DETECTED' : 'NO_CHANGES';

                      const body = `
                      ## Chromatic

                      Status: **${statusText}** ${statusIcon}
                      Detected changes: **${changesCount}**

                      To review visual changes, visit the link below:  
                      [${chromaticUrl}](${chromaticUrl})
                      `;

                      await github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: body
                      });
