name: 'Chromatic (automatic)'
on:
    pull_request_review:
        types: [submitted]
jobs:
    count_approvals:
        name: Count approvals
        uses: ./.github/workflows/pr-approvals.yml
        with:
            pull-number: ${{ github.event.pull_request.number }}
            min-approval-count: 0
        secrets:
            github-token: ${{ secrets.GITHUB_TOKEN }}
    run_chromatic:
        name: Run Chromatic
        needs: count_approvals
        if: needs.count_approvals.outputs.is_approved == 'true'
        uses: ./.github/workflows/chromatic.yml
