name: 'Chromatic (manual)'
on:
    pull_request:
        types: [labeled]
jobs:
    run_chromatic:
        name: Run Chromatic
        if: ${{ github.event.label.name == 'chromatic' }}
        uses: ./.github/workflows/chromatic.yml
