name: 'Chromatic (manual)'
on:
    issue_comment:
        types: [created]
jobs:
    check_comments:
        name: Check PR comments
        runs-on: ubuntu-latest
        if: contains(github.event.comment.html_url, '/pull/')
        steps:
            - name: Post results
              if: contains(github.event.comment.body, '/chromatic')
              uses: actions/github-script@v7
              with:
                  script: |
                      github.rest.issues.createComment({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.issue.number,
                        body: 'MANUAL ACTION EXECUTED'
                      })
